name: ECR build-push and applying tf-stack

on: 
  workflow_call:
    inputs:
      app_unit:
        type: string
        required: true
      ecr-repo-name:
        type: string
        required: true
      values-file:
        type: string
        required: true
    secrets:
      github_pat:
        required: true
      
jobs:
  Apply-cfn-stack:
    runs-on: self-hosted
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: org-548/infra
          path: infra
          token: ${{ secrets.github_pat }}

      - name: Up cloudformation stack
        working-directory: infra
        run: |
          aws cloudformation create-stack --stack-name gthub-oidc-conf \
            --capabilities CAPABILITY_NAMED_IAM --template-body file://cfn-template.yaml
  
  Apply-tf-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repo for server unit
        if: ${{ inputs.app_unit != 'client' }}
        uses: actions/checkout@v4

      - name: Checkout primary repo for client unit
        if: ${{ inputs.app_unit == 'client' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}    

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: org-548/infra
          path: infra
          token: ${{ secrets.github_pat }}

      - name: Setup Git 
        shell: bash
        run: |
          echo "Git setup"
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'    

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/role-for-github-oidc
          aws-region: eu-north-1

      - name: Apply Terraform infrastructure
        id: get-output
        working-directory: infra/terraform
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve

      - name: Inject api-url in appropriate file
        if: ${{ inputs.app_unit == 'client' }}
        run: |
          aws elb describe-load-balancers > out.json
          export API_URL=$(jq -r '.[] | .[] | .DNSName' out.json)
          envsubst < index.htm > index.html    

      - name: Get short SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2      

      - name: Build, tag and push image to AWS ECR
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: ${{ inputs.ecr-repo-name }}
          IMAGE_TAG: ${{ env.SHORT_SHA }}
        run: |
          echo ${{ env.SHORT_SHA }}
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Unset variable value and delete .html file
        if: ${{ inputs.app_unit == 'client' }}
        run: |
          unset API_URL
          rm index.html    

      - name: Update tag in appropriate values.yaml file
        working-directory: infra/charts/values
        run: |
          echo ${{ env.SHORT_SHA }}
          if [[ "$(yq eval .deploy.image.tag ${{ inputs.values-file }})" != "${{ env.SHORT_SHA }}" ]]; then
            sed -E -i'' "s/(.*tag: ).*/\1${{ env.SHORT_SHA }}/" '${{ inputs.values-file }}'
          fi
          
      - name: Commit and push changes
        shell: bash
        working-directory: infra/charts/values
        env:
          GITHUB_TOKEN: ${{ secrets.github_pat }}
          COMMIT_MESSAGE: "Update image-tag with ${{ env.SHORT_SHA }}"
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            echo "Commit and push to second repo"
            git add .
            git commit -m "${{ env.COMMIT_MESSAGE }}"
            git push
          else
            echo "No changes"
            exit 0
          fi

          
