name: App deployment with Kubernetes

on: 
  workflow_call:
    inputs:
      app_unit:
        type: string
        required: true
    secrets:
      github_pat:
        required: true 
      
jobs:
  Apply-kubernetes-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repo for server unit
        if: ${{ inputs.app_unit != 'client' }}
        uses: actions/checkout@v4

      - name: Checkout primary repo for client unit
        if: ${{ inputs.app_unit == 'client' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: org-548/infra
          path: infra
          token: ${{ secrets.github_pat }}
          
      - name: Setup Git
        shell: bash
        run: |
          echo "Git setup"
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/${{ vars.OIDC_ROLE_NAME }}
          aws-region: eu-north-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.32.3'
          
      - name: Udpate kubeconfig
        run: aws eks update-kubeconfig --region eu-north-1 --name first-eks

      - name: Ingress controller deployment
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml

      - name: Setup Helmwave
        run: |
          export VERSION=0.19.3
          wget -c https://github.com/helmwave/helmwave/releases/download/v$VERSION/helmwave_${VERSION}_linux_amd64.tar.gz -O - | tar -xz
          mv helmwave /usr/local/bin/

      - name: Helmwave build/up
        id: get-hw-output
        continue-on-error: true
        working-directory: infra/charts
        run: |
          helmwave up --build --yml --kubedog | tail -n 5 >> helmwave.out
          diff helmwave.out error.txt
          if [[ $? -eq 0 ]]; then
            echo "Expected temporary error during the first helmwave-build: Continue >>>"
          else
            exit 1
        
            
