name: App deploymnet with Kubernetes

on: 
  workflow_call:
    secrets:
      github_pat:
        required: true
      region:
        required: true  
      
jobs:
  Apply-kubernetes-stack:
    runs-on: ubuntu-latest
 
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout primary repo
        uses: actions/checkout@v4

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: org-548/infra
          path: infra
          token: ${{ secrets.github_pat }}
          
      - name: Git Setup  
        shell: bash
        run: |
          echo "Git setup"
          pwd
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/role-for-github-oidc
          aws-region: ${{ secrets.region }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.32.3'
        id: install    
          
      - name: Udpate kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.region }} --name first-eks

      - name: Ingress controller deployment
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml

      - name: Setup Helmwave
        run: |
          export VERSION=0.19.3
          wget -c https://github.com/helmwave/helmwave/releases/download/v$VERSION/helmwave_${VERSION}_linux_amd64.tar.gz -O - | tar -xz
          mv helmwave /usr/local/bin/

      - name: Helmwave build/up
        id: get-hw-output
        continue-on-error: true
        working-directory: infra/charts
        run: |
          helmwave up --build --kubedog | tail -n 6 >> helmwave.out
          diff helmwave.out error.txt
          if [[ $? -eq 0 ]]; then
            echo "Expected temporary error: Continue >>>"
          else
            exit 1
            
      
